apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-config
data:
  # WEBSERVER [NGINX] ENVIRONMENT VARIABLES
  # THE PUBLIC HUB WEBSERVER HOST WILL BE SERVED AS A SUBJECT ALTERNATIVE NAME (SAN) WITHIN THE
  # DEFAULT, SERVED CERTIFICATE. THIS VALUE SHOULD BE CHANGED TO THE PUBLICALLY-FACING
  # HOSTNAME THAT USERS WILL ENTER IN THEIR BROWSER IN ORDER TO ACCESS HUB.
  # For OpenShift users this is the value of your exposed route.
  PUBLIC_HUB_WEBSERVER_HOST: "localhost"

  # IF THE HOST PORT IS CHANGED, THE PUBLIC HUB WEBSERVER PORT VALUE SHOULD BE EQUALLY CHANGED
  PUBLIC_HUB_WEBSERVER_PORT: "443"

  # IF THE CONTAINER PORT IS CHANGED, THE HUB WEBSERVER PORT VALUE SHOULD BE EQUALLY CHANGED
  HUB_WEBSERVER_PORT: "8443"

  # Set this to "1" if IPv6 should be disabled. This is not usually needed.
  IPV4_ONLY: "0"

  # Hub DB Properties.
  # These usually do not need to be changed.
  HUB_POSTGRES_ENABLE_SSL: "true"
  HUB_POSTGRES_USER: "blackduck_user"
  HUB_POSTGRES_ADMIN: "blackduck"

  # HOSTS THAT WON'T GO THROUGH A PROXY
  HUB_PROXY_NON_PROXY_HOSTS: "solr"

  # Proxy settings for Hub to get to outside services.
  # Uncomment and set these if an outgoing proxy is required.
  #HUB_PROXY_SCHEME:
  #HUB_PROXY_HOST: 
  #HUB_PROXY_PORT: 
  #HUB_PROXY_USER: 

  # For NTLM Proxies
  #HUB_PROXY_WORKSTATION:
  #HUB_PROXY_DOMAIN:
    
  # DO NOT REMOVE HUB_VERSION!!
  HUB_VERSION: 4.6.1
